In [2]:
import pandas as pd
from glob import glob

In [3]:
ls ..

DATA-Behavior/      DATA-Preprocessed/  SCRIPTS-preprocess/
DATA-EEG/           SCRIPTS-analysis/   SCRIPTS-task/

In [10]:
sub_files = sorted(glob('../DATA-Behavior/*_wInt.csv'))

In [11]:
sub_files

['../DATA-Behavior/p-007_task-changeDetection_Exp1_wInt.csv',
 '../DATA-Behavior/p-008_task-changeDetection_Exp1_wInt.csv']

In [21]:
for f in sub_files:
    main_beh = pd.read_csv(f.replace('_wInt',''))
    main_beh.to_csv(f.replace('_wInt','_Main')) # move to _Main
    
    main_beh.index.name = 'original_trial_index'
    
    int_beh = pd.read_csv(f)
    int_beh.index.name = 'original_trial_index'
    
    full_beh = pd.concat([main_beh, int_beh]).reset_index()
    full_beh.to_csv(f.replace('_wInt',''))

In [19]:
main_beh

,targetCloud_bins_1,targetCloud_bins_2,targetCloud_bins_3,targetCloud_color,targetCloud_nDots,otherCloud_color,otherCloud_bins_1,otherCloud_bins_2,otherCloud_bins_3,otherCloud_nDots,...,probe_bins_2,probe_bins_3,probe_color,probe_nDots,change_type,port_codes,CorrectResponse,Response,ResponseTime,ChoiceAcc
original_trial_index,,,,,,,,,,,,,,,,,,,,,
0,4,NaN,NaN,green,17,blue,4.0,NaN,NaN,12,...,NaN,NaN,green,17,0,221,RightArrow,RightArrow,2.224754,1
1,8,1.0,2.0,green,12,blue,7.0,NaN,NaN,22,...,NaN,NaN,green,12,2,222,LeftArrow,LeftArrow,2.143595,1
2,7,8.0,1.0,blue,13,green,6.0,7.0,8.0,19,...,8.0,1.0,blue,13,0,223,RightArrow,RightArrow,1.707633,1
3,3,4.0,5.0,green,43,blue,NaN,NaN,NaN,0,...,4.0,5.0,green,43,0,213,RightArrow,RightArrow,1.237228,1
4,7,8.0,1.0,blue,16,green,2.0,NaN,NaN,19,...,8.0,1.0,blue,16,0,222,RightArrow,RightArrow,3.379271,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1531,3,4.0,5.0,blue,15,green,6.0,7.0,8.0,22,...,4.0,5.0,blue,15,1,223,LeftArrow,LeftArrow,0.613190,1
1532,6,NaN,NaN,blue,24,green,NaN,NaN,NaN,0,...,NaN,NaN,blue,24,1,211,LeftArrow,LeftArrow,4.625993,1
1533,3,NaN,NaN,green,22,blue,4.0,5.0,6.0,14,...,NaN,NaN,green,22,0,222,RightArrow,RightArrow,0.791989,1
1534,7,NaN,NaN,blue,12,green,3.0,4.0,5.0,17,...,NaN,NaN,blue,12,0,222,RightArrow,RightArrow,4.264390,1
1535,7,8.0,1.0,green,16,blue,5.0,6.0,7.0,20,...,8.0,1.0,green,16,1,223,LeftArrow,LeftArrow,1.079380,1

In [20]:
pd.read_csv(f.replace('_wInt','_Main'))

,original_trial_index,targetCloud_bins_1,targetCloud_bins_2,targetCloud_bins_3,targetCloud_color,targetCloud_nDots,otherCloud_color,otherCloud_bins_1,otherCloud_bins_2,otherCloud_bins_3,...,probe_bins_2,probe_bins_3,probe_color,probe_nDots,change_type,port_codes,CorrectResponse,Response,ResponseTime,ChoiceAcc
0,0,4,NaN,NaN,green,17,blue,4.0,NaN,NaN,...,NaN,NaN,green,17,0,221,RightArrow,RightArrow,2.224754,1
1,1,8,1.0,2.0,green,12,blue,7.0,NaN,NaN,...,NaN,NaN,green,12,2,222,LeftArrow,LeftArrow,2.143595,1
2,2,7,8.0,1.0,blue,13,green,6.0,7.0,8.0,...,8.0,1.0,blue,13,0,223,RightArrow,RightArrow,1.707633,1
3,3,3,4.0,5.0,green,43,blue,NaN,NaN,NaN,...,4.0,5.0,green,43,0,213,RightArrow,RightArrow,1.237228,1
4,4,7,8.0,1.0,blue,16,green,2.0,NaN,NaN,...,8.0,1.0,blue,16,0,222,RightArrow,RightArrow,3.379271,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1531,1531,3,4.0,5.0,blue,15,green,6.0,7.0,8.0,...,4.0,5.0,blue,15,1,223,LeftArrow,LeftArrow,0.613190,1
1532,1532,6,NaN,NaN,blue,24,green,NaN,NaN,NaN,...,NaN,NaN,blue,24,1,211,LeftArrow,LeftArrow,4.625993,1
1533,1533,3,NaN,NaN,green,22,blue,4.0,5.0,6.0,...,NaN,NaN,green,22,0,222,RightArrow,RightArrow,0.791989,1
1534,1534,7,NaN,NaN,blue,12,green,3.0,4.0,5.0,...,NaN,NaN,blue,12,0,222,RightArrow,RightArrow,4.264390,1
1535,1535,7,8.0,1.0,green,16,blue,5.0,6.0,7.0,...,8.0,1.0,green,16,1,223,LeftArrow,LeftArrow,1.079380,1